### ISSUE TITLE
[Feature Request]Deprecated Warning

### ISSUE THREAD

**Issue by tenkoma** [memory-agape/github-php-function-jumper#18]
Displaying deprecated warnings may help with code reviews.

**Comment by memory-agape** [comment]
Which do you like to show the deprecated message place?
- Show strike line to the deprecated method on source code.
- Show popup-window

**Comment by tenkoma** [comment]
I think later options are good.
Some projects will have no problem using deprecated functions.

**Comment by memory-agape** [comment]
Okay 👍  I'll implement it.

**Comment by memory-agape** [comment]
Implemented it.
